### ISSUE TITLE
'NIKFontAwesomeIconTypes.h' file not found

### ISSUE THREAD

**Issue by Ben305** [nschum/FontAwesomeIconFactory#10]
I try to use FontAwesomeIconFactory in my project using CocoaPods.

But it fails with the following error message:
<project path...>/Pods/Headers/Public/FontAwesomeIconFactory/NIKFontAwesomeIconTraits.h:1:9:'NIKFontAwesomeIconTypes.h' file not found

The file 'NIKFontAwesomeIconTypes.h' is not included in Pods/Headers/Public/FontAwesomeIconFactory

Other components can be used successfully from CocoaPods in the same app.

**Comment by nschum** [comment]
Oups. I wonder why my local tests didn't catch that. I'll fix it ASAP.

Until then, version 2.0.0 should still work.
