### ISSUE TITLE
How to use FontAwesomeIconFactory with other class?

### ISSUE THREAD

**Issue by DesmondPang** [nschum/FontAwesomeIconFactory#11]
I wonder to know how to use FontAwesomeIconFactory and other library/class at the same time. For example, I need to create a button and I set a button effect class in its custom class in storyboard. However, I also need to use FontAwesomeIconFactory to generate the image for this button. How can I do that? I have tried to use NIKFontAwesomeImageView to create the image and than assign to the button.image but it failed. Thank you.

**Comment by nschum** [comment]
That's exactly what the Demo app [does](https://github.com/nschum/FontAwesomeIconFactory/blob/fa2f395501e975fa716c62442449acf3be872459/FontAwesomeIconFactoryDemo/FontAwesomeIconFactoryDemo/FirstViewController.m#L47-L70).
