### ISSUE TITLE
Storyboard Extensions

### ISSUE THREAD

**Issue by tonimoeckel** [nschum/FontAwesomeIconFactory#5]
Hi there!
I just created some UIControls to work with your Factory. It's pretty small, easy and simple. Have a look at it. I'am very happy to fork and share it with your repo!

[https://github.com/quemb/FontAwesomeIconFactory-Extensions](FontAwesomeIconFactory-Extensions)

**Comment by nschum** [comment]
Sorry for the delay on this. With IBInspectable the KVC method became the obvious choice.

Version 2.0 adds this and includes live preview in Interface Builder, too.
