### ISSUE TITLE
Icons generated are being clipped on right side

### ISSUE THREAD

**Issue by Geosef** [nschum/FontAwesomeIconFactory#9]
When generating the images to set for a button, icons that are somewhat wider than they are tall clip on the right side.

Check mark:
![image](https://cloud.githubusercontent.com/assets/5271942/8385430/1d50bbfe-1c16-11e5-9460-5a50d7c5045d.png)

Down arrow:
![image](https://cloud.githubusercontent.com/assets/5271942/8385474/51d79aa0-1c16-11e5-9d11-0c71df799aa3.png)

**Comment by nschum** [comment]
Thanks.
Does this change work for you?

**Comment by nschum** [comment]
Thanks.
Does this change work for you?

**Comment by Geosef** [comment]
Yep! Appreciate the fix.
